import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { AppSidebar } from "@/components/sidebar/app-sidebar";
import { SidebarInset, SidebarProvider} from "@/components/ui/sidebar";
import ReduxProvider from "@/lib/Provider";
import Breadcrumb from "@/components/sidebar/breadcrumb";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >  
      <SidebarProvider>
      <AppSidebar />
      <SidebarInset>
      <Breadcrumb/> 
      <main>
        <ReduxProvider>{children}</ReduxProvider>
      </main>
      </SidebarInset>
    </SidebarProvider>
      </body>
    </html>
  );
}
