import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { AppSidebar } from "@/components/sidebar/app-sidebar";
import { SidebarInset, SidebarProvider } from "@/components/ui/sidebar";
import ReduxProvider from "@/lib/Provider";
import Breadcrumb from "@/components/sidebar/breadcrumb";

import AuthProvider from "@/lib/auth-provider";
import { Layout } from "lucide-react";
import LayoutWraper from "@/components/layout/LayoutWrapper";
import AuthDebug from "@/components/debug/AuthDebug";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <AuthProvider>
          <LayoutWraper>{children}</LayoutWraper>
          <AuthDebug />
        </AuthProvider>
      </body>
    </html>
  );
}
